# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: echo "running tests..."
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: echo "helloooo!!!!"

workflows:
  # Name of workflow
  build_test_and_lint:
    # List of jobs that will run
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere